### ISSUE TITLE
Hello i have an error please

### ISSUE THREAD

**Issue by Dany-LF** [Ankrad/Discord-Bot-List#10]
[2019-11-28 05:22:36] MongoParseError: Invalid connection string

MONGO_DB_URL=http://test678-shard-00-00-7bzzc.gcp.mongodb.net:27017/

Can I have the instructions for mongodb?

**Comment by Dany-LF** [comment]
Can someone help me??

**Comment by ClearlyElevated** [comment]
the connection link is simply invalid. There isnt anymore to it then what it says. providing full logs as i mentioned before actually helps. cant expect to receive help if u cannot do the work to show us some of the issues. post them here. https://haste-bin.tk

**Comment by Dany-LF** [comment]
Sorry i never use mongo db...


https://www.paste-bin.tk/acovubuhow.http

**Comment by Ankrad** [comment]
Your connection string is invalid. Make sure you've copied and pasted the exact connection url that you get from MongoDB atlas.

**Comment by Dany-LF** [comment]
dbl-shard-00-00-7bzzc.gcp.mongodb.net:27017 is the exact url of mongodb atlas...

![testscreen](https://user-images.githubusercontent.com/53636771/70472127-d9ed1580-1ace-11ea-8db4-67d09ffcfb8e.png)

**Comment by ClearlyElevated** [comment]
That's clearing not the connection string

**Comment by ClearlyElevated** [comment]
We aren't going to do it all for you dude. I gave you the answer and you still as lazily as before asked for help. When you get a response with something you don't know
 And possibly not even know the next 3+ answer you need to get on Google. Not even one is gonna hold your hand thoughout this process. It took me months to figure out how to self host. But once I learned code it came as second nature. If you.seen the amount of messages like this are more often then not

**Comment by ClearlyElevated** [comment]
They're you go. That should be easier http://lmgtfy.com/?q=How%20can%20I%20find%20my%20MongoDB%20connection%20string&%20set%20it%20up%20for%20use%20with%20node.js
