### ISSUE TITLE
What's the token in me?token=

### ISSUE THREAD

**Issue by bruxy9** [Ankrad/Discord-Bot-List#21]
(domain.com/me?token='token' ) - is that the discord user account token, and if it is, is that against Discord Terms of Service? Or how I can disable it? 
 
 btw, is that token needed?

**Comment by Ankrad** [comment]
It's not user token; it should be part of the redirect when you click on a link and it's the bearer token from the API. You can disable it by storing it in the cookies and getting it with `res.cookies` in the backend.
