### ISSUE TITLE
edit function

### ISSUE THREAD

**Issue by YasmijnVels** [Ankrad/Discord-Bot-List#22]
anyone can edit your bot.
could this be secured that the bot owner can only edit it?

and the Bot widget doesn't work either, he says not found.

**Comment by YasmijnVels** [comment]
if you use the new update then can you secure the edit page 
then can only the bot owners edit the bot
put this in this file `src/Routes/bots/edit.js`

const { Router } = require("express");
const bodyParser = require("body-parser");
const is = require('is-html');
const { getUser } = require("@utils/discordApi.js");

const route = Router();

route.get("/:id", async (req, res, next) => {
    let [user, tk] = await getUser(req.cookies["refresh_token"]);
    res.cookie('refresh_token', tk, {httpOnly: true});
    let bot = JSON.parse(req.app.get('client').settings.get('bots')).find(u => u.id === req.params.id);

    if (!bot) return res.sendStatus(404);
    if (!bot.owners.includes(user.id)) return res.redirect(`/error?e=owner`);
    res.render("edit/index", { bot: bot });
});

module.exports = route;

**Comment by Ankrad** [comment]
Done!
