### ISSUE TITLE
Sending DM to the user when a bot gets added.

### ISSUE THREAD

**Issue by YasmijnVels** [Ankrad/Discord-Bot-List#23]
i get this error when i will send a private message after an command.
how can i solve this problem

this is the code for the send message
message.author.send(`Your bot \`${res.name}\` has been approved! :tada:`);

C:\Users\Administrator\.pm2\logs\index-error.log last 15 lines:
0|index    |   path: '/channels/668477405178101780/messages',
0|index    |   code: 50007,
0|index    |   httpStatus: 403
0|index    | }
0|index    | [2020-01-22 23:02:45] [EVENT] C:\Users\Administrator\Desktop\1\luna
\node_modules\klasa\src\events\unhandledRejection.js
0|index    | [2020-01-22 23:02:45] Error [ERR_UNHANDLED_ERROR]: Unhandled error.
 ('Uncaught Promise Error: \n' +
0|index    | [2020-01-22 23:02:45]   'DiscordAPIError: Cannot send messages to t
his user\n' +
0|index    | [2020-01-22 23:02:45]   '    at RequestHandler.execute (C:\\Users\\
Administrator\\Desktop\\1\\luna\\node_modules\\discord.js\\src\\rest\\RequestHan
dler.js:170:25)\n' +
0|index    | [2020-01-22 23:02:45]   '    at processTicksAndRejections (internal
/process/task_queues.js:93:5)')
0|index    | [2020-01-22 23:02:45]     at KlasaClient.emit (events.js:199:17)
0|index    | [2020-01-22 23:02:45]     at module.exports.run (C:\Users\Administr
ator\Desktop\1\luna\node_modules\klasa\src\events\unhandledRejection.js:12:15)
0|index    | [2020-01-22 23:02:45]     at module.exports._run (C:\Users\Administ
rator\Desktop\1\luna\node_modules\klasa\src\lib\structures\Event.js:101:15)
0|index    | [2020-01-22 23:02:45]     at process.emit (events.js:215:7)
0|index    | [2020-01-22 23:02:45]     at processPromiseRejections (internal/pro
cess/promises.js:201:33)
0|index    | [2020-01-22 23:02:45]     at processTicksAndRejections (internal/pr
ocess/task_queues.js:94:32)

**Comment by namekinggamerboy** [comment]
Yes sam show me errors and prot not working in (3000) prot but view not working

**Comment by namekinggamerboy** [comment]
But my hosting glitch

**Comment by YasmijnVels** [comment]
i hosted it on me home server :)

**Comment by Ankrad** [comment]
That depends entirely on context. Where are you placing that line of code?

**Comment by YasmijnVels** [comment]
in the bot command code verifiy.js
but is not working since the new update

const { Command } = require('klasa');
const { MessageEmbed } = require('discord.js');
var modLog;

module.exports = class extends Command {
    constructor(...args) {
        super(...args, {
            aliases: ["v"],
            permissionLevel: 8,
            usage: '[User:user]'
        });
    }

    async run(message, [user]) {
        if (!user || !user.bot) return message.channel.send(`Ping a **bot**.`);
        let updated = JSON.parse(message.client.settings.get('bots'));
        updated.find(u => u.id === user.id).state = "verified";
        message.client.settings.update("bots", JSON.stringify(updated));
        let res = updated.find(u => u.id === user.id);
        let e = new MessageEmbed()
            .setTitle('Bot approved')
            .addField(`Bot`, `<@${res.id}>`, true)
            .addField(`Owner`, `<@${res.owners[0]}>`, true)
            .addField("Mod", message.author, true)
            .setThumbnail(res.logo)
            .setTimestamp()
            .setColor(0x26ff00)
        modLog.send(e);
        modLog.send(`<@${res.owners[0]}>`).then(m => { m.delete() })

        message.guild.members.fetch(message.client.users.find(u => u.id === res.owners[0])).then(owner => {
            owner.roles.add(message.guild.roles.get(process.env.BOT_DEVELOPER_ROLE_ID))
        })
        message.guild.members.fetch(message.client.users.find(u => u.id === res.id)).then(bot => {
            bot.roles.set([process.env.BOT_ROLE_ID, process.env.VERIFIED_ROLE_ID, process.env.UNMUTED_ROLE_ID]); // Bot and verified and Unmuted
        })
        message.channel.send(`Verified \`${res.name}\``);
        message.author.send(`Your bot \`${res.name}\` has been approved! :tada:`);
    }

    async init() {
        modLog = this.client.guilds.get(process.env.GUILD_ID).channels.get(process.env.MOD1_LOG_ID);
    }
};

**Comment by namekinggamerboy** [comment]
Remove thumbnail and code working and wait to refresh your server and add bot so your refresh your server??

**Comment by namekinggamerboy** [comment]
And show me error:-
```
[2020-01-25 02:15:39] Uncaught Promise Error: 
[2020-01-25 02:15:39] Error: Cannot find module '/app/src/Utils/discordapi'
[2020-01-25 02:15:39] Require stack:
[2020-01-25 02:15:39] - /app/src/Routes/api/bots/submit.js
[2020-01-25 02:15:39] - /app/src/Routes/api/bots.js
[2020-01-25 02:15:39] - /app/src/Routes/api/index.js
[2020-01-25 02:15:39] - /app/src/Routes/index.js
[2020-01-25 02:15:39] - /app/src/Structures/App.js
[2020-01-25 02:15:39] - /app/src/index.js
[2020-01-25 02:15:39]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
[2020-01-25 02:15:39]     at Function.Module._resolveFilename (/rbd/pnpm-volume/1ee719b1-fad5-4465-87ac-a51598473aef/node_modules/.registry.npmjs.org/module-alias/2.2.2/node_modules/module-alias/index.js:49:29)
[2020-01-25 02:15:39]     at Function.Module._load (internal/modules/cjs/loader.js:526:27)
[2020-01-25 02:15:39]     at Module.require (internal/modules/cjs/loader.js:666:19)
[2020-01-25 02:15:39]     at require (internal/modules/cjs/helpers.js:16:16)
[2020-01-25 02:15:39]     at Object.<anonymous> (/app/src/Routes/api/bots/submit.js:4:29)
[2020-01-25 02:15:39]     at Module._compile (internal/modules/cjs/loader.js:759:30)
[2020-01-25 02:15:39]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
[2020-01-25 02:15:39]     at Module.load (internal/modules/cjs/loader.js:628:32)
[2020-01-25 02:15:39]     at Function.Module._load (internal/modules/cjs/loader.js:555:12)```

**Comment by YasmijnVels** [comment]
is there a way if you add the bot that the bot sends you a private message that it has been put on the list pending verification?
and the same for when you verify it.
or if you reject the bot?

**Comment by Ankrad** [comment]
@YasmijnVels Yes, it is possible. Currently it logs it in the mod log channel. To get the owner of the bot, use `this.client.users.get(ID)`, and the ID is usually in the modlog, when it pings the user. Then you can send a message to the user's DM

**Comment by Ankrad** [comment]
@namekinggamerboy Please open another issue

**Comment by namekinggamerboy** [comment]
Ok

**Comment by YasmijnVels** [comment]
and how can I make sure he sends a private message as soon as you add the bot to the site?
that he is waiting for verification?

**Comment by Ankrad** [comment]
This
> @YasmijnVels Yes, it is possible. Currently it logs it in the mod log channel. To get the owner of the bot, use `this.client.users.get(ID)`, and the ID is usually in the modlog, when it pings the user. Then you can send a message to the user's DM

**Comment by YasmijnVels** [comment]
@Ankrad that only works for bot commands!
not if someone adds a bot to the site!

**Comment by Ankrad** [comment]
File: `src/Routes/api/bots/submit.js`
Lines: In between lines 62 and 63.

```js
req.app.get('client').users.get(newBot.owners[0]).send(`Thank you for submitting <@${newBot.id}>. etc...`)
```

**Comment by YasmijnVels** [comment]
thank you
