### ISSUE TITLE
Single line used in database?

### ISSUE THREAD

**Issue by YasmijnVels** [Ankrad/Discord-Bot-List#24]
is it possible not to put everything in 1 line in the database?

**Comment by Ankrad** [comment]
@YasmijnVels Yes, but the way Klasa works with arrays is weird and inconsistent, so I just went for a string containing the array.

**Comment by YasmijnVels** [comment]
and how in which file should I change that?

**Comment by YasmijnVels** [comment]
oh okay 
are you going to change it so that it is no longer in 1 file.
that would be nice

**Comment by Ankrad** [comment]
Probably not, because Klasa arrays system doesn't work properly and making my own data basing system would really not be required here.

Also, it's not just one file, it's every file that uses the database.
