### ISSUE TITLE
again an discord api error

### ISSUE THREAD

**Issue by YasmijnVels** [Ankrad/Discord-Bot-List#28]
C:\Users\yasmijn\.pm2\logs\index-error.log last 15 lines:
0|index    |   path: '/channels/668477405178101780/messages',
0|index    |   code: 50007,
0|index    |   httpStatus: 403
0|index    | }
0|index    | [2020-01-26 13:35:55] [EVENT] C:\Users\yasmijn\Desktop\Discord-Bot-List-master\node_modules\klasa\src\events\unhandledRejection.js
0|index    | [2020-01-26 13:35:55] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \n' +
0|index    | [2020-01-26 13:35:55]   'DiscordAPIError: Cannot send messages to this user\n' +
0|index    | [2020-01-26 13:35:55]   '    at RequestHandler.execute (C:\\Users\\yasmijn\\Desktop\\Discord-Bot-List-master\\node_modules\\discord.js\\src\\rest\\RequestHandler.js:170:25)\n' +
0|index    | [2020-01-26 13:35:55]   '    at processTicksAndRejections (internal/process/task_queues.js:93:5)')
0|index    | [2020-01-26 13:35:55]     at KlasaClient.emit (events.js:199:17)
0|index    | [2020-01-26 13:35:55]     at module.exports.run (C:\Users\yasmijn\Desktop\Discord-Bot-List-master\node_modules\klasa\src\events\unhandledRejection.js:12:15)
0|index    | [2020-01-26 13:35:55]     at module.exports._run (C:\Users\yasmijn\Desktop\Discord-Bot-List-master\node_modules\klasa\src\lib\structures\Event.js:101:15)
0|index    | [2020-01-26 13:35:55]     at process.emit (events.js:215:7)
0|index    | [2020-01-26 13:35:55]     at processPromiseRejections (internal/process/promises.js:201:33)
0|index    | [2020-01-26 13:35:55]     at processTicksAndRejections (internal/process/task_queues.js:94:32)

**Comment by Ankrad** [comment]
That means that the user has their DMs blocked in discord settings or server settings. Make sure you "Allow direct messages from server members" in privacy settings

**Comment by YasmijnVels** [comment]
@Ankrad it working and now io have this error

C:\Users\yasmijn\.pm2\logs\index-error.log last 15 lines:
0|index    |     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
0|index    |   [Symbol(code)]: 'INVALID_TYPE'
0|index    | }
0|index    | [2020-01-26 13:52:44] [EVENT] C:\Users\yasmijn\Desktop\Discord-Bot-List-master\node_modules\klasa\src\events\unhandledRejection.js
0|index    | [2020-01-26 13:52:44] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \n' +
0|index    | [2020-01-26 13:52:44]   'TypeError [INVALID_TYPE]: Supplied roles is not an Array or Collection of Roles or Snowflakes.\n' +
0|index    | [2020-01-26 13:52:44]   '    at Map.remove (C:\\Users\\yasmijn\\Desktop\\Discord-Bot-List-master\\node_modules\\discord.js\\src\\stores\\GuildMemberRoleStore.js:102:15)\n' +
0|index    | [2020-01-26 13:52:44]   '    at C:\\Users\\yasmijn\\Desktop\\Discord-Bot-List-master\\src\\Bot\\commands\\Bots\\unverify.js:95:23\n' +
0|index    | [2020-01-26 13:52:44]   '    at processTicksAndRejections (internal/process/task_queues.js:93:5)')
0|index    | [2020-01-26 13:52:44]     at KlasaClient.emit (events.js:199:17)
0|index    | [2020-01-26 13:52:44]     at module.exports.run (C:\Users\yasmijn\Desktop\Discord-Bot-List-master\node_modules\klasa\src\events\unhandledRejection.js:12:15)
0|index    | [2020-01-26 13:52:44]     at module.exports._run (C:\Users\yasmijn\Desktop\Discord-Bot-List-master\node_modules\klasa\src\lib\structures\Event.js:101:15)
0|index    | [2020-01-26 13:52:44]     at process.emit (events.js:215:7)
0|index    | [2020-01-26 13:52:44]     at processPromiseRejections (internal/process/promises.js:201:33)
0|index    | [2020-01-26 13:52:44]     at processTicksAndRejections (internal/process/task_queues.js:94:32)

**Comment by YasmijnVels** [comment]
again @Ankrad 

C:\Users\Administrator\.pm2\logs\index-error.log last 15 lines:
0|index    |   path: '/guilds/668068009285386259/roles/668068059390672906',
0|index    |   code: 50013,
0|index    |   httpStatus: 403
0|index    | }
0|index    | [2020-01-26 16:13:03] [EVENT] C:\Users\Administrator\Desktop\1\luna
\node_modules\klasa\src\events\unhandledRejection.js
0|index    | [2020-01-26 16:13:03] Error [ERR_UNHANDLED_ERROR]: Unhandled error.
 ('Uncaught Promise Error: \n' +
0|index    | [2020-01-26 16:13:03]   'DiscordAPIError: Missing Permissions\n' +
0|index    | [2020-01-26 16:13:03]   '    at RequestHandler.execute (C:\\Users\\
Administrator\\Desktop\\1\\luna\\node_modules\\discord.js\\src\\rest\\RequestHan
dler.js:170:25)\n' +
0|index    | [2020-01-26 16:13:03]   '    at processTicksAndRejections (internal
/process/task_queues.js:93:5)')
0|index    | [2020-01-26 16:13:03]     at KlasaClient.emit (events.js:199:17)
0|index    | [2020-01-26 16:13:03]     at module.exports.run (C:\Users\Administr
ator\Desktop\1\luna\node_modules\klasa\src\events\unhandledRejection.js:12:15)
0|index    | [2020-01-26 16:13:03]     at module.exports._run (C:\Users\Administ
rator\Desktop\1\luna\node_modules\klasa\src\lib\structures\Event.js:101:15)
0|index    | [2020-01-26 16:13:03]     at process.emit (events.js:215:7)
0|index    | [2020-01-26 16:13:03]     at processPromiseRejections (internal/pro
cess/promises.js:201:33)
0|index    | [2020-01-26 16:13:03]     at processTicksAndRejections (internal/pr
ocess/task_queues.js:94:32)

**Comment by Ankrad** [comment]
> DiscordAPIError: Missing Permissions
Make sure the bot has enough permissions in the server

**Comment by YasmijnVels** [comment]
the bot has all permissions but continues to indicate that error.

And do you also happen to know how I could do this?

```
            let name = document.createElement("h2")
            name.classList.add('title')
            name.innerHTML = bot.name
            if (bot.botverified === "1") icon1.src = name.html('<img><%= process.env.DOMAIN %>/assets/img/verified.png"></img>')
            banner.appendChild(name)```

**Comment by Ankrad** [comment]
> the bot has all permissions but continues to indicate that error.

Make sure the bot's role is higher than the other roles

**Comment by YasmijnVels** [comment]
thanks it work
