### ISSUE TITLE
Html not support

### ISSUE THREAD

**Issue by namekinggamerboy** [Ankrad/Discord-Bot-List#29]
![Screenshot_2020-01-27-08-23-58-069](https://user-images.githubusercontent.com/53903319/73147645-7058b300-40de-11ea-9d83-cfacb6b7c602.jpeg)

**Comment by Ankrad** [comment]
What?

**Comment by namekinggamerboy** [comment]
How to item frame url please help me only url send hot web view send

**Comment by namekinggamerboy** [comment]
![Screenshot_2020-01-29-13-17-36-005](https://user-images.githubusercontent.com/53903319/73337143-befe7c80-4299-11ea-8cb8-852af58f3fe2.jpeg)
Please ex. Me
![Screenshot_2020-01-29-13-16-52-905](https://user-images.githubusercontent.com/53903319/73337100-ac844300-4299-11ea-914e-e591931545d2.jpeg)
