### ISSUE TITLE
api/embed/your id is not working

### ISSUE THREAD

**Issue by YasmijnVels** [Ankrad/Discord-Bot-List#30]
![21b3edb90b5ee3d3d4274a42604a1952](https://user-images.githubusercontent.com/59023524/73156397-fcb6a600-40dd-11ea-877c-331dcf2aa813.png)

how can i fix it

**Comment by Ankrad** [comment]
I think i fixed this in the last commit: 85d0868

**Comment by YasmijnVels** [comment]
thanks
