### ISSUE TITLE
klasa text send

### ISSUE THREAD

**Issue by YasmijnVels** [Ankrad/Discord-Bot-List#32]
why he send this text in a channel?

![image](https://user-images.githubusercontent.com/59023524/73256318-0285b780-41c2-11ea-8267-cca8c9ca2146.png)

**Comment by namekinggamerboy** [comment]
Type `_info` so information about

**Comment by Ankrad** [comment]
Removed: 4d924c6

**Comment by YasmijnVels** [comment]
thank you
