### ISSUE TITLE
api count

### ISSUE THREAD

**Issue by YasmijnVels** [Ankrad/Discord-Bot-List#34]
how can i use the api count
where should I use that in which files?

![image](https://user-images.githubusercontent.com/59023524/73429344-c1191780-433b-11ea-8f72-86bbbb9b78b1.png)

**Comment by Ankrad** [comment]
The bot that wants to post its server count has to use that

**Comment by YasmijnVels** [comment]
I don't understand him completely can you explain it better?
or how do images show how it works?

**Comment by YasmijnVels** [comment]
so then I have to make an api bot and then do that code in the index.js?
and which npm packages does it need? @Ankrad

**Comment by YasmijnVels** [comment]
???

**Comment by Ankrad** [comment]
It's part of the bot. No, you don't need an API bot. The person that uploads a discord bot needs to worry about that, not you. They'll understand it. It's just posting stats for that bot. They're sending you their bot's server count
