### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Xclash** [Ankrad/Discord-Bot-List#7]
Pls Help 
/root/Discord-Bot-List/server.js:491
    .add(8, ({ client, author }) => process.env.ADMIN_USERS.split(' ').includes(author.id));
     ^

TypeError: Client.defaultPermissionLevels.add is not a function
    at Object.<anonymous> (/root/Discord-Bot-List/server.js:491:6)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-bot-list@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the discord-bot-list@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-12T16_56_34_631Z-debug.log

**Comment by ClearlyElevated** [comment]
do you have node installed?

**Comment by ClearlyElevated** [comment]
> Pls Help
> /root/Discord-Bot-List/server.js:491
> .add(8, ({ client, author }) => process.env.ADMIN_USERS.split(' ').includes(author.id));
> ^
> 
> TypeError: Client.defaultPermissionLevels.add is not a function
> at Object. (/root/Discord-Bot-List/server.js:491:6)
> at Module._compile (internal/modules/cjs/loader.js:778:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> at Module.load (internal/modules/cjs/loader.js:653:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
> at startup (internal/bootstrap/node.js:283:19)
> at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! discord-bot-list@1.0.0 start: `node server.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the discord-bot-list@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /root/.npm/_logs/2019-10-12T16_56_34_631Z-debug.log

also. Can you do pm2 logs --lines 500 and send the output to pastebin

**Comment by ClearlyElevated** [comment]
did u try to edit something. it tells you right there what your issue is. "Client.defaultPermissionLevels.Add is not a function

**Comment by Xclash** [comment]
Okay, Pls Help mongodb

**Comment by Xclash** [comment]
url

**Comment by ClearlyElevated** [comment]
what??? @Xclash 

if you expect to get help from me or the owner of this repo you should take the time to provide some backround on the issue. because i dont know what mongodb url help means. i would assume you dont know how to obtain your mongo url. and in that case youve come to the wrong place my friend. this is for issues or support for the bot itself. mongodb isnt core

**Comment by ClearlyElevated** [comment]
[start here! ](https://lmgtfy.com/?q=How+to+obtain+a+mongodb+url%3F&p=1&iie=1)

**Comment by Ankrad** [comment]
Are you sure you installed the dependencies properly?

**Comment by ClearlyElevated** [comment]
sounds like it cant find djs. its crazy how much ive learned just by trial and error with your project. thanks buddy!
